### ISSUE TITLE
To-Do (before summit)

### ISSUE THREAD

**Issue by pathakhimadri** [CheckMaths/CheckMaths.github.io#8]
- [ ] Font formatting of second section
- [ ] Change the `our work` to `our team` with photos; potentially with consistent background
- [ ] Change main section to highlight the achievements of checkmath
- [ ] Add another section about the news of achievements
- [ ] Format the newsletter section
